### ISSUE TITLE
[Improve] - Add eslint to this project

### ISSUE THREAD

**Issue by gurpreet-legend** [gurpreet-legend/Face-Recognition-Brainiac-Frontend#3]
### Improvements:
- [ ] Add `eslint` to this project to make the code more robust and readable
- [ ] Add linting scripts to `package.json` for easy access to lint commands

Here are steps to add eslint to Node projects, you can refer this article:
https://dev.to/drsimplegraffiti/eslint-configuration-for-node-project-275l

> ***Note:*** Make sure to lint check all the files as well

**Comment by Bwc9876** [comment]
Could I get this issue assigned to me?

**Comment by gurpreet-legend** [comment]
@Bwc9876 go ahead!
